# Mapping from Yahoo Finance balance sheet keys → your DB model fields
YFINANCE_TO_DB_FIELDS = {
    "Accounts Payable": "accounts_payable",
    "Accounts Receivable": "accounts_receivable",
    "Accumulated Depreciation": "accumulated_depreciation",
    "Available For Sale Securities": "available_for_sale_securities",
    "Capital Lease Obligations": "capital_lease_obligations",
    "Capital Stock": "capital_stock",
    "Cash And Cash Equivalents": "cash_and_cash_equivalents",
    "Cash Cash Equivalents And Short Term Investments": "cash_cash_equivalents_and_short_term_investments",
    "Cash Equivalents": "cash_equivalents",
    "Cash Financial": "cash_financial",
    "Commercial Paper": "commercial_paper",
    "Common Stock": "common_stock",
    "Common Stock Equity": "common_stock_equity",
    "Current Assets": "current_assets",
    "Current Capital Lease Obligation": "current_capital_lease_obligation",
    "Current Debt": "current_debt",
    "Current Debt And Capital Lease Obligation": "current_debt_and_capital_lease_obligation",
    "Current Deferred Liabilities": "current_deferred_liabilities",
    "Current Deferred Revenue": "current_deferred_revenue",
    "Current Liabilities": "current_liabilities",
    "Gains Losses Not Affecting Retained Earnings": "gains_losses_not_affecting_retained_earnings",
    "Gross PPE": "gross_ppe",
    "Income Tax Payable": "income_tax_payable",
    "Inventory": "inventory",
    "Invested Capital": "invested_capital",
    "Investmentin Financial Assets": "investment_in_financial_assets",
    "Investments And Advances": "investments_and_advances",
    "Land And Improvements": "land_and_improvements",
    "Leases": "leases",
    "Long Term Capital Lease Obligation": "long_term_capital_lease_obligation",
    "Long Term Debt": "long_term_debt",
    "Long Term Debt And Capital Lease Obligation": "long_term_debt_and_capital_lease_obligation",
    "Machinery Furniture Equipment": "machinery_furniture_equipment",
    "Net Debt": "net_debt",
    "Net PPE": "net_ppe",
    "Net Tangible Assets": "net_tangible_assets",
    "Non Current Deferred Assets": "non_current_deferred_assets",
    "Non Current Deferred Taxes Assets": "non_current_deferred_taxes_assets",
    "Ordinary Shares Number": "ordinary_shares_number",
    "Other Current Assets": "other_current_assets",
    "Other Current Borrowings": "other_current_borrowings",
    "Other Current Liabilities": "other_current_liabilities",
    "Other Equity Adjustments": "other_equity_adjustments",
    "Other Investments": "other_investments",
    "Other Non Current Assets": "other_non_current_assets",
    "Other Non Current Liabilities": "other_non_current_liabilities",
    "Other Properties": "other_properties",
    "Other Receivables": "other_receivables",
    "Other Short Term Investments": "other_short_term_investments",
    "Payables": "payables",
    "Payables And Accrued Expenses": "payables_and_accrued_expenses",
    "Properties": "properties",
    "Receivables": "receivables",
    "Retained Earnings": "retained_earnings",
    "Share Issued": "share_issued",
    "Stockholders Equity": "stockholders_equity",
    "Tangible Book Value": "tangible_book_value",
    "Total Assets": "total_assets",
    "Total Capitalization": "total_capitalization",
    "Total Debt": "total_debt",
    "Total Equity Gross Minority Interest": "total_equity_gross_minority_interest",
    "Total Liabilities Net Minority Interest": "total_liabilities_net_minority_interest",
    "Total Non Current Assets": "total_non_current_assets",
    "Total Non Current Liabilities Net Minority Interest": "total_non_current_liabilities_net_minority_interest",
    "Total Tax Payable": "total_tax_payable",
    "Tradeand Other Payables Non Current": "trade_and_other_payables_non_current",
    "Treasury Shares Number": "treasury_shares_number",
    "Working Capital": "working_capital",
}
