from sqlalchemy import create_engine, Column, Integer, String, Float
from sqlalchemy.ext.declarative import declarative_base
from ..db.base import Base

class BalanceSheet(Base):
    __tablename__ = 'balance_sheet'

    ticker = Column(String, primary_key=True, index=True)  # Stock ticker (e.g., AAPL, TSLA)
    year = Column(Integer, primary_key=True)  # Reporting year (e.g., 2024, 2023)

    treasury_shares_number = Column(Float, nullable=True)
    ordinary_shares_number = Column(Float, nullable=True)
    share_issued = Column(Float, nullable=True)
    net_debt = Column(Float, nullable=True)
    total_debt = Column(Float, nullable=True)
    tangible_book_value = Column(Float, nullable=True)
    invested_capital = Column(Float, nullable=True)
    working_capital = Column(Float, nullable=True)
    net_tangible_assets = Column(Float, nullable=True)
    capital_lease_obligations = Column(Float, nullable=True)
    common_stock_equity = Column(Float, nullable=True)
    total_capitalization = Column(Float, nullable=True)
    total_equity_gross_minority_interest = Column(Float, nullable=True)
    stockholders_equity = Column(Float, nullable=True)
    gains_losses_not_affecting_retained_earnings = Column(Float, nullable=True)
    other_equity_adjustments = Column(Float, nullable=True)
    retained_earnings = Column(Float, nullable=True)
    capital_stock = Column(Float, nullable=True)
    common_stock = Column(Float, nullable=True)
    total_liabilities_net_minority_interest = Column(Float, nullable=True)
    total_non_current_liabilities_net_minority_interest = Column(Float, nullable=True)
    other_non_current_liabilities = Column(Float, nullable=True)
    trade_and_other_payables_non_current = Column(Float, nullable=True)
    long_term_debt_and_capital_lease_obligation = Column(Float, nullable=True)
    long_term_capital_lease_obligation = Column(Float, nullable=True)
    long_term_debt = Column(Float, nullable=True)
    current_liabilities = Column(Float, nullable=True)
    other_current_liabilities = Column(Float, nullable=True)
    current_deferred_liabilities = Column(Float, nullable=True)
    current_deferred_revenue = Column(Float, nullable=True)
    current_debt_and_capital_lease_obligation = Column(Float, nullable=True)
    current_capital_lease_obligation = Column(Float, nullable=True)
    current_debt = Column(Float, nullable=True)
    other_current_borrowings = Column(Float, nullable=True)
    commercial_paper = Column(Float, nullable=True)
    payables_and_accrued_expenses = Column(Float, nullable=True)
    payables = Column(Float, nullable=True)
    total_tax_payable = Column(Float, nullable=True)
    income_tax_payable = Column(Float, nullable=True)
    accounts_payable = Column(Float, nullable=True)
    total_assets = Column(Float, nullable=True)
    total_non_current_assets = Column(Float, nullable=True)
    other_non_current_assets = Column(Float, nullable=True)
    non_current_deferred_assets = Column(Float, nullable=True)
    non_current_deferred_taxes_assets = Column(Float, nullable=True)
    investments_and_advances = Column(Float, nullable=True)
    other_investments = Column(Float, nullable=True)
    investment_in_financial_assets = Column(Float, nullable=True)
    available_for_sale_securities = Column(Float, nullable=True)
    net_ppe = Column(Float, nullable=True)
    accumulated_depreciation = Column(Float, nullable=True)
    gross_ppe = Column(Float, nullable=True)
    leases = Column(Float, nullable=True)
    other_properties = Column(Float, nullable=True)
    machinery_furniture_equipment = Column(Float, nullable=True)
    land_and_improvements = Column(Float, nullable=True)
    properties = Column(Float, nullable=True)
    current_assets = Column(Float, nullable=True)
    other_current_assets = Column(Float, nullable=True)
    inventory = Column(Float, nullable=True)
    receivables = Column(Float, nullable=True)
    other_receivables = Column(Float, nullable=True)
    accounts_receivable = Column(Float, nullable=True)
    cash_and_cash_equivalents_and_short_term_investments = Column(Float, nullable=True)
    other_short_term_investments = Column(Float, nullable=True)
    cash_and_cash_equivalents = Column(Float, nullable=True)
    cash_equivalents = Column(Float, nullable=True)
    cash_financial = Column(Float, nullable=True)